services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secretpassword
      RABBITMQ_LOGS: "-"  # Log to stdout
      RABBITMQ_LOG_LEVEL: warning
    networks:
      - coffee-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - rabbitmq
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
    networks:
      - coffee-net

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    depends_on:
      - gateway
    environment:
      PYTHONUNBUFFERED: 1
      DATA_DIR: /app/.data
      SERVER_ADDRESS: gateway:5000
      CLIENT_ID: client1
      BATCH_MAX_AMOUNT: 100
    volumes:
      - ./data:/app/.data
    networks:
      - coffee-net

  cleaner_transactions:
    build: ./cleaner
    container_name: cleaner_transactions
    depends_on:
      - gateway
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_queue
      QUEUE_OUT: transactions_cleaned
      DATA_TYPE: transactions
    networks:
      - coffee-net

  cleaner_transaction_items:
    build: ./cleaner
    container_name: cleaner_transaction_items
    depends_on:
      - gateway
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transaction_items_queue
      QUEUE_OUT: transaction_items_cleaned
      DATA_TYPE: transaction_items
    networks:
      - coffee-net

  cleaner_users:
    build: ./cleaner
    container_name: cleaner_users
    depends_on:
      - gateway
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: users_queue
      QUEUE_OUT: users_cleaned
      DATA_TYPE: users
    networks:
      - coffee-net

  cleaner_stores:
    build: ./cleaner
    container_name: cleaner_stores
    depends_on:
      - gateway
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: stores_queue
      QUEUE_OUT: stores_cleaned
      DATA_TYPE: stores
    networks:
      - coffee-net

  cleaner_menu_items:
    build: ./cleaner
    container_name: cleaner_menu_items
    depends_on:
      - gateway
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: menu_items_queue
      QUEUE_OUT: menu_items_cleaned
      DATA_TYPE: menu_items
    networks:
      - coffee-net

networks:
  coffee-net:
    driver: bridge