services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secretpassword
      RABBITMQ_LOGS: "-"  # Log to stdout
      RABBITMQ_LOG_LEVEL: warning
    networks:
      - coffee-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      PYTHONPATH: /app
      GATEWAY_HOST: 0.0.0.0
      GATEWAY_PORT: 5000
      QUEUE_IN: results
    networks:
      - coffee-net

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    depends_on:
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      DATA_DIR: /app/.data
      SERVER_ADDRESS: gateway:5000
      CLIENT_ID: client1
      BATCH_MAX_AMOUNT: 5000
    volumes:
      - ./data:/app/.data
      - ./results:/app/results
    networks:
      - coffee-net

  cleaner_transactions:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    container_name: cleaner_transactions
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_queue
      QUEUE_OUT: transactions_cleaned
      DATA_TYPE: transactions
    networks:
      - coffee-net

  cleaner_transaction_items:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    container_name: cleaner_transaction_items
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transaction_items_queue
      QUEUE_OUT: transaction_items_cleaned
      DATA_TYPE: transaction_items
    networks:
      - coffee-net

  cleaner_users:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    container_name: cleaner_users
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: users_queue
      QUEUE_OUT: users_cleaned
      DATA_TYPE: users
    networks:
      - coffee-net

  cleaner_stores:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    container_name: cleaner_stores
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: stores_queue
      QUEUE_OUT: stores_cleaned_q3,stores_cleaned_q4
      DATA_TYPE: stores
    networks:
      - coffee-net

  cleaner_menu_items:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    container_name: cleaner_menu_items
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: menu_items_queue
      QUEUE_OUT: menu_items_cleaned
      DATA_TYPE: menu_items
    networks:
      - coffee-net

  temporal_filter_transactions:
    build:
      context: .
      dockerfile: filter/Dockerfile
    container_name: temporal_filter_transactions
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_cleaned
      QUEUE_OUT: transactions_filtered_Q1,transactions_filtered_Q3, transactions_filtered_Q4
      DATA_TYPE: transactions
      FILTER_TYPE: temporal
    networks:
      - coffee-net

  temporal_filter_transaction_items:
    build:
      context: .
      dockerfile: filter/Dockerfile
    container_name: temporal_filter_transaction_items
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transaction_items_cleaned
      QUEUE_OUT: transaction_items_filtered_Q2
      DATA_TYPE: transaction_items
      FILTER_TYPE: temporal
    networks:
      - coffee-net

  amount_filter_transactions:
    build:
      context: .
      dockerfile: filter/Dockerfile
    container_name: amount_filter_transactions
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_filtered_Q1
      QUEUE_OUT: transactions_filtered_Q1_b
      DATA_TYPE: transactions
      FILTER_TYPE: amount
      MIN_AMOUNT: 75

    networks:
      - coffee-net

  cleaner_transactions_q4:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    container_name: cleaner_transactions_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      temporal_filter_transactions:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_filtered_Q4
      QUEUE_OUT: transactions_cleaned_Q4
      DATA_TYPE: transactions_q4
    networks:
      - coffee-net

  joiner_q1:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    container_name: joiner_q1
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_filtered_Q1_b
      QUEUE_OUT: sort_q1_request
      OUTPUT_FILE: /app/output/q1_unsorted.csv
      QUERY_TYPE: q1
    volumes:
      - ./output:/app/output
    networks:
          - coffee-net

  sorter_q1:
    build:
      context: .
      dockerfile: sort/Dockerfile
    container_name: sorter_q1
    depends_on:
      rabbitmq:
        condition: service_healthy
      joiner_q1:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sort_q1_request
      INPUT_FILE: /app/output/q1_unsorted.csv
      OUTPUT_FILE: /app/output/q1.csv
      DATA_TYPE: q1
      COMPLETION_QUEUE: sender_q1_signal
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net
  
  grouper_q2:
    build:
      context: .
      dockerfile: grouper/Dockerfile
    container_name: grouper_q2
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transaction_items_filtered_Q2
      COMPLETION_QUEUE: topper_q2_signal
      GROUPER_MODE: q2
    volumes:
      - ./grouper/temp:/app/temp
    networks:
      - coffee-net

  grouper_q3:
    build:
      context: .
      dockerfile: grouper/Dockerfile
    container_name: grouper_q3
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_filtered_Q3
      GROUPER_MODE: q3
      COMPLETION_QUEUE: topper_q3_signal
    volumes:
      - ./grouper/temp:/app/temp
    networks:
      - coffee-net

  grouper_q4:
    build:
      context: .
      dockerfile: grouper/Dockerfile
    container_name: grouper_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      GROUPER_MODE: q4
      QUEUE_IN: transactions_cleaned_Q4
      COMPLETION_QUEUE: topper_q4_signal
    volumes:
      - ./grouper/temp:/app/temp
    networks:
      - coffee-net

  topper_q2:
    build:
      context: .
      dockerfile: topper/Dockerfile
    container_name: topper_q2
    depends_on:
      rabbitmq:
        condition: service_healthy
      grouper_q2:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: topper_q2_signal
      INPUT_DIR: /app/temp/transaction_items_filtered_Q2
      OUTPUT_FILE: /app/topper_temp/q2_top1.csv
      TOP_N: 1
      COMPLETION_QUEUE: sender_grouper_q2_signal
      TOPPER_MODE: Q2
    volumes:
      - ./grouper/temp:/app/temp
      - ./topper/temp:/app/topper_temp
    networks:
      - coffee-net


  topper_q3:
    build:
      context: .
      dockerfile: topper/Dockerfile
    container_name: topper_q3
    depends_on:
      rabbitmq:
        condition: service_healthy
      grouper_q3:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: topper_q3_signal
      INPUT_DIR: /app/temp/transactions_filtered_Q3
      OUTPUT_FILE: /app/topper_temp/q3_top1.csv
      TOP_N: 1
      COMPLETION_QUEUE: sender_grouper_q3_signal
      TOPPER_MODE: Q3
    volumes:
      - ./grouper/temp:/app/temp
      - ./topper/temp:/app/topper_temp
    networks:
      - coffee-net

  topper_q4:
    build:
      context: .
      dockerfile: topper/Dockerfile
    container_name: topper_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      grouper_q4:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: topper_q4_signal
      INPUT_DIR: /app/temp/transactions_cleaned_Q4
      OUTPUT_FILE: /app/topper_temp/q4_top3.csv
      TOP_N: 3
      COMPLETION_QUEUE: sender_grouper_q4_signal
      TOPPER_MODE: Q4
    volumes:
      - ./grouper/temp:/app/temp
      - ./topper/temp:/app/topper_temp
    networks:
      - coffee-net

  sender_grouper_q4:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_grouper_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      topper_q4:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_grouper_q4_signal
      QUEUE_OUT: resultados_groupby_q4
      INPUT_FILE: /app/topper_temp/topper_q4_signal/q4_top3.csv
      BATCH_SIZE: 5000
      QUERY_TYPE: q4
    volumes:
      - ./topper/temp:/app/topper_temp
    networks:
      - coffee-net

  joiner_q4:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    container_name: joiner_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      cleaner_stores:
        condition: service_started
      cleaner_users:
        condition: service_started
      sender_grouper_q4:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      MULTIPLE_QUEUES: stores_cleaned_q4,resultados_groupby_q4,users_cleaned
      QUEUE_OUT: sort_q4_request
      OUTPUT_FILE: /app/output/q4_unsorted.csv
      QUERY_TYPE: q4
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net

  joiner_q2:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    container_name: joiner_q2
    depends_on:
      rabbitmq:
        condition: service_healthy
      cleaner_menu_items:
        condition: service_started
      sender_grouper_q2:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      MULTIPLE_QUEUES: resultados_groupby_q2,menu_items_cleaned
      QUEUE_OUT: sender_q2_a_signal, sender_q2_b_signal
      OUTPUT_FILE: /app/output/q2_a.csv, /app/output/q2_b.csv
      QUERY_TYPE: q2
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net

  sorter_q4:
    build:
      context: .
      dockerfile: sort/Dockerfile
    container_name: sorter_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      joiner_q4:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sort_q4_request
      INPUT_FILE: /app/output/q4_unsorted.csv
      OUTPUT_FILE: /app/output/q4.csv
      COMPLETION_QUEUE: sender_q4_signal
      DATA_TYPE: q4
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net
      
  sender_q4:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_q4
    depends_on:
      rabbitmq:
        condition: service_healthy
      sorter_q4:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_q4_signal
      QUEUE_OUT: results
      INPUT_FILE: /app/output/q4.csv
      QUERY_TYPE: q4
      INCLUDE_HEADERS: true
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net
    
  sender_q2_a:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_q2_a
    depends_on:
      rabbitmq:
        condition: service_healthy
      joiner_q2:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_q2_a_signal
      QUEUE_OUT: results
      INPUT_FILE: /app/output/q2_a.csv
      QUERY_TYPE: q2_a
      INCLUDE_HEADERS: true
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net

  sender_q2_b:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_q2_b
    depends_on:
      rabbitmq:
        condition: service_healthy
      joiner_q2:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_q2_b_signal
      QUEUE_OUT: results
      INPUT_FILE: /app/output/q2_b.csv
      QUERY_TYPE: q2_b
      INCLUDE_HEADERS: true
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net

  sender_grouper_q2:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_grouper_q2
    depends_on:
      rabbitmq:
        condition: service_healthy
      topper_q2:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_grouper_q2_signal
      QUEUE_OUT: resultados_groupby_q2
      INPUT_FILE: /app/topper_temp/topper_q2_signal/q2_top1.csv
      BATCH_SIZE: 5000
      QUERY_TYPE: q2
    volumes:
      - ./topper/temp:/app/topper_temp
    networks:
      - coffee-net

  sender_grouper_q3:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_grouper_q3
    depends_on:
      rabbitmq:
        condition: service_healthy
      topper_q3:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_grouper_q3_signal
      QUEUE_OUT: resultados_groupby_q3
      INPUT_FILE: /app/topper_temp/topper_q3_signal/q3_top1.csv
      BATCH_SIZE: 5000
      QUERY_TYPE: q3
    volumes:
      - ./topper/temp:/app/topper_temp
    networks:
      - coffee-net

  sender_q1:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_q1
    depends_on:
      rabbitmq:
        condition: service_healthy
      sorter_q1:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_q1_signal
      QUEUE_OUT: results
      INPUT_FILE: /app/output/q1.csv
      QUERY_TYPE: q1
      INCLUDE_HEADERS: true
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net
  

  joiner_q3:
    build:
      context: .
      dockerfile: joiner/Dockerfile
    container_name: joiner_q3
    depends_on:
      rabbitmq:
        condition: service_healthy
      cleaner_stores:
        condition: service_started
      sender_grouper_q3:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      MULTIPLE_QUEUES: resultados_groupby_q3,stores_cleaned_q3
      QUEUE_OUT: sort_q3_request
      OUTPUT_FILE: /app/output/q3_unsorted.csv
      QUERY_TYPE: q3
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net

  sorter_q3:
    build:
      context: .
      dockerfile: sort/Dockerfile
    container_name: sorter_q3
    depends_on:
      rabbitmq:
        condition: service_healthy
      joiner_q3:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sort_q3_request
      INPUT_FILE: /app/output/q3_unsorted.csv
      OUTPUT_FILE: /app/output/q3.csv
      COMPLETION_QUEUE: sender_q3_signal
      DATA_TYPE: q3
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net
  
  sender_q3:
    build:
      context: .
      dockerfile: sender/Dockerfile
    container_name: sender_q3
    depends_on:
      rabbitmq:
        condition: service_healthy
      sorter_q3:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: sender_q3_signal
      QUEUE_OUT: results
      INPUT_FILE: /app/output/q3.csv
      QUERY_TYPE: q3
      INCLUDE_HEADERS: true
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net
    
networks:
  coffee-net:
    driver: bridge