version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secretpassword
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - coffee-net

  shm:
    build:
      context: .
      dockerfile: SHM/Dockerfile
    container_name: shm
    environment:
      PYTHONUNBUFFERED: 1
      HM_STATE_PATH: /app/output/hashmap_state.json
      HM_HOST: 0.0.0.0
      HM_PORT: 9100
    volumes:
      - ./output:/app/output
    networks:
      - coffee-net

  wsm:
    build:
      context: .
      dockerfile: WSM/Dockerfile
    container_name: wsm
    environment:
      PYTHONUNBUFFERED: 1
      STATE_FILE_PATH: /app/output/worker_states.json   # ✅ nueva variable de entorno
      HOST: 0.0.0.0
      PORT: 9000
    volumes:
      - ./output_wsm:/app/output                        # ✅ ruta persistente en tu host
    networks:
      - coffee-net


  sender_transactions:
    build:
      context: .
      dockerfile: tests/sender/Dockerfile
    container_name: sender_transactions
    depends_on:
      rabbitmq:
        condition: service_healthy
      wsm:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_OUT: transactions_queue
    networks:
      - coffee-net


  receiver_transactions:
    build:
      context: .
      dockerfile: tests/receiver/Dockerfile
    container_name: receiver_transactions
    depends_on:
      cleaner_transactions:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_cleaned
    volumes:
      - ./output_test:/app/output   # 👈 guarda los resultados persistentes
    networks:
      - coffee-net




  # ☕ Cleaners de transacciones (replicas)
  cleaner_transactions:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      sender_transactions:
        condition: service_started
      wsm:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_queue
      QUEUE_OUT: transactions_cleaned
      DATA_TYPE: transactions
      WSM_HOST: wsm
      WSM_PORT: 9000
    networks:
      - coffee-net
    deploy:
      replicas: 5  # ← Compose ignora "deploy" fuera de Swarm, ver nota abajo

networks:
  coffee-net:
    driver: bridge
