version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secretpassword
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - coffee-net

  # 🧠 Worker State Manager
  wsm:
    build:
      context: .
      dockerfile: WSM/Dockerfile
    container_name: wsm
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./output_wsm:/app/output
    networks:
      - coffee-net

  sender_transactions:
    build:
      context: .
      dockerfile: tests/sender/Dockerfile
    container_name: sender_transactions
    depends_on:
      rabbitmq:
        condition: service_healthy
      wsm:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_OUT: transactions_queue
    networks:
      - coffee-net


  receiver_transactions:
    build:
      context: .
      dockerfile: tests/receiver/Dockerfile
    container_name: receiver_transactions
    depends_on:
      cleaner_transactions:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_cleaned
    networks:
      - coffee-net




  # ☕ Cleaners de transacciones (replicas)
  cleaner_transactions:
    build:
      context: .
      dockerfile: cleaner/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      sender_transactions:
        condition: service_started
      wsm:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: secretpassword
      QUEUE_IN: transactions_queue
      QUEUE_OUT: transactions_cleaned
      DATA_TYPE: transactions
      WSM_HOST: wsm
      WSM_PORT: 9000
    networks:
      - coffee-net
    deploy:
      replicas: 5  # ← Compose ignora "deploy" fuera de Swarm, ver nota abajo

networks:
  coffee-net:
    driver: bridge
